### ISSUE TITLE
General problem

### ISSUE THREAD

**Issue by leonardofmed** [morganherlocker/geojson2shape#2]
The default usage method don't work, it throws an error:
 `ENOENT: no such file or directory, open 'C:\Users\randomuser\Desktop\geojson2shp\polygons.dbf'`

Also, the "zip" option don't do anything.

**Comment by morganherlocker** [comment]
@leonardofmed do you have ogr2ogr installed?

**Comment by leonardofmed** [comment]
Hi, I manage to convert using ogr2ogr directly with the following:
```
args = ["ogr2ogr", "-f", "ESRI Shapefile", "-a_srs", "EPSG:31982", "./processed_files/filename.shp", "geojsonFile.geojson"]
subprocess.Popen(args).wait()
```
